services:
  nginx:
    container_name: ${APP_ID}-nginx
    build:
      context: .
      dockerfile: Dockerfile.production
      target: nginx
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf:delegated
    restart: always
    tty: true
    depends_on:
      - php
    networks:
      - custom_network

  php:
    container_name: ${APP_ID}-php
    build:
      context: .
      dockerfile: Dockerfile.production
      target: php
    volumes:
      - ./:/var/www/html:delegated
    restart: always
    tty: true
    depends_on:
      - mysql
    networks:
      - custom_network

  mysql:
    container_name: ${APP_ID}-mysql
    build:
      context: .
      dockerfile: Dockerfile.production
      target: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - custom_volume:/var/lib/mysql
    restart: always
    tty: true
    networks:
      - custom_network

  phpmyadmin:
    container_name: ${APP_ID}-phpmyadmin
    build:
      context: .
      dockerfile: Dockerfile.production
      target: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
    restart: always
    tty: true
    depends_on:
      - mysql
    networks:
      - custom_network

  mailpit:
    container_name: ${APP_ID}-mailpit
    build:
      context: .
      dockerfile: Dockerfile.production
      target: mailpit
    ports:
      - "${SMTP_PORT}:1025"
      - "${MAILPIT_PORT}:8025"
    restart: always
    tty: true
    networks:
      - custom_network

networks:
  custom_network:
    name: ${APP_ID}-network
volumes:
  custom_volume:
    name: ${APP_ID}-volume
