services:
  nginx:
    container_name: ${APP_NAME}-nginx
    build:
      context: .
      target: nginx
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./:/var/www/html:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:delegated
      - certbot:/etc/letsencrypt
    tty: true
    depends_on:
      - php
    networks:
      - custom_network

  certbot:
    container_name: ${APP_NAME}-certbot
    build:
      context: .
      target: certbot
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN}
    volumes:
      - ./:/var/www/html:delegated
      - certbot:/etc/letsencrypt
    depends_on:
      - nginx
    networks:
      - custom_network

  php:
    container_name: ${APP_NAME}-php
    build:
      context: .
      target: php
    volumes:
      - ./:/var/www/html:delegated
    tty: true
    depends_on:
      - mysql
    networks:
      - custom_network

  mysql:
    container_name: ${APP_NAME}-mysql
    build:
      context: .
      target: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - custom_volume:/var/lib/mysql
    tty: true
    networks:
      - custom_network

  phpmyadmin:
    container_name: ${APP_NAME}-phpmyadmin
    build:
      context: .
      target: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    tty: true
    depends_on:
      - mysql
    networks:
      - custom_network

networks:
  custom_network:
    name: ${APP_NAME}-network
volumes:
  custom_volume:
    name: ${APP_NAME}-volume
  certbot:
    name: ${APP_NAME}-certbot
