services:
  filament-nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filament-nginx.rule=Host(`filament.hkit.pro`)"
      - "traefik.http.routers.filament-nginx.entrypoints=websecure"
      - "traefik.http.routers.filament-nginx.tls.certresolver=myresolver"
    container_name: filament-nginx
    image: filament-nginx
    build:
      context: .
      dockerfile: Dockerfile.production
      target: nginx
    volumes:
      - ./:/var/www/html:delegated
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf:delegated
    restart: always
    tty: true
    depends_on:
      - filament-php
    networks:
      - proxy

  filament-php:
    container_name: filament-php
    image: filament-php
    build:
      context: .
      dockerfile: Dockerfile.production
      target: php
    volumes:
      - ./:/var/www/html:delegated
    restart: always
    tty: true
    depends_on:
      - filament-mysql
    networks:
      - proxy

  filament-mysql:
    container_name: filament-mysql
    image: filament-mysql
    build:
      context: .
      dockerfile: Dockerfile.production
      target: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - database:/var/lib/mysql
    restart: always
    tty: true
    networks:
      - proxy

  filament-phpmyadmin:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filament-phpmyadmin.rule=Host(`filament.db.hkit.pro`)"
      - "traefik.http.routers.filament-phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.filament-phpmyadmin.tls.certresolver=myresolver"
    container_name: filament-phpmyadmin
    image: filament-phpmyadmin
    build:
      context: .
      dockerfile: Dockerfile.production
      target: phpmyadmin
    environment:
      PMA_HOST: filament-mysql
    restart: always
    tty: true
    depends_on:
      - filament-mysql
    networks:
      - proxy

volumes:
  database:
    name: filament-db

networks:
  proxy:
    external: true
