# nginx
FROM nginx:alpine AS nginx
ENV UID=1000
ENV GID=1000
ENV USER=filament
ENV GROUP=filament
RUN addgroup -g ${GID} --system ${GROUP}
RUN adduser -u ${UID} --system ${USER} -G ${GROUP} -D -s /bin/sh
RUN sed -i "s/user  nginx/user ${USER}/g" /etc/nginx/nginx.conf
WORKDIR /var/www/html

# php
FROM php:fpm-alpine AS php
COPY --from=composer /usr/bin/composer /usr/local/bin/composer
ENV UPLOAD_MAX_FILESIZE=10M
ENV POST_MAX_SIZE=20M
RUN echo "upload_max_filesize=${UPLOAD_MAX_FILESIZE}" >> /usr/local/etc/php/conf.d/uploads.ini
RUN echo "post_max_size=${POST_MAX_SIZE}" >> /usr/local/etc/php/conf.d/uploads.ini
ENV UID=1000
ENV GID=1000
ENV USER=filament
ENV GROUP=filament
RUN addgroup -g ${GID} --system ${GROUP}
RUN adduser -u ${UID} --system ${USER} -G ${GROUP} -D -s /bin/sh
RUN sed -i "s/user = www-data/user = ${USER}/g" /usr/local/etc/php-fpm.d/www.conf
RUN sed -i "s/group = www-data/group = ${GROUP}/g" /usr/local/etc/php-fpm.d/www.conf
RUN apk update
RUN apk upgrade
RUN apk add --no-cache font-noto font-noto-cjk git nodejs npm
RUN docker-php-ext-install exif
RUN apk add --no-cache libpng-dev libjpeg-turbo-dev freetype-dev
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install gd
RUN apk add --no-cache icu-dev
RUN docker-php-ext-install intl
RUN docker-php-ext-install pdo_mysql
RUN apk add --no-cache libzip-dev
RUN docker-php-ext-install zip
RUN apk add --no-cache autoconf build-base
RUN pecl install pcov
RUN docker-php-ext-enable pcov
WORKDIR /var/www/html
USER ${USER}

# mysql
FROM mysql:lts AS mysql

# phpmyadmin
FROM phpmyadmin AS phpmyadmin

# mailpit
FROM axllent/mailpit AS mailpit
