#!/bin/bash

APP_DIR="$(git rev-parse --show-toplevel)"

cp "$APP_DIR/.env.example" "$APP_DIR/.env"

ENV_FILE="$APP_DIR/.env"

. "$ENV_FILE"

if [ "$(uname -s)" = 'Darwin' ]; then
    sed -i '' 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' "$ENV_FILE"
    sed -i '' 's/# DB_HOST=127.0.0.1/DB_HOST=mysql/' "$ENV_FILE"
    sed -i '' 's/# DB_PORT=3306/DB_PORT=3306/' "$ENV_FILE"
    sed -i '' 's/# DB_DATABASE=laravel/DB_DATABASE=laravel/' "$ENV_FILE"
    sed -i '' 's/# DB_USERNAME=root/DB_USERNAME=root/' "$ENV_FILE"
    sed -i '' 's/# DB_PASSWORD=/DB_PASSWORD=root/' ""$ENV_FILE""

elif [ "$(uname -s)" = 'Linux' ]; then
    sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' "$ENV_FILE"
    sed -i 's/# DB_HOST=127.0.0.1/DB_HOST=mysql/' "$ENV_FILE"
    sed -i 's/# DB_PORT=3306/DB_PORT=3306/' "$ENV_FILE"
    sed -i 's/# DB_DATABASE=laravel/DB_DATABASE=laravel/' "$ENV_FILE"
    sed -i 's/# DB_USERNAME=root/DB_USERNAME=root/' "$ENV_FILE"
    sed -i 's/# DB_PASSWORD=/DB_PASSWORD=root/' ""$ENV_FILE""
fi

APP_NAME=$(echo "$APP_NAME" | tr 'A-Z' 'a-z')

docker compose -f "$APP_DIR/docker/compose.yml" -p "$APP_NAME" up -d

docker exec "$APP_NAME-php" /bin/sh -c "composer install; php artisan key:generate; php artisan storage:link; php artisan migrate:fresh --seed --force; npm install; npm run build"

docker exec -it "$APP_NAME-php" /bin/sh
